apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: akshaygirpunje
    provider: github
    repository: spring-boot-http-gradle
  managedFields:
  - apiVersion: jenkins.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:owner: {}
          f:provider: {}
          f:repository: {}
      f:spec:
        .: {}
        f:description: {}
        f:httpCloneURL: {}
        f:org: {}
        f:provider: {}
        f:providerKind: {}
        f:providerName: {}
        f:repo: {}
        f:scheduler:
          .: {}
          f:kind: {}
          f:name: {}
        f:url: {}
    manager: jx
    operation: Update
    time: "2021-04-29T17:21:45Z"
  name: akshaygirpunje-spring-boot-http-gradle
spec:
  description: Imported application for akshaygirpunje/spring-boot-http-gradle
  httpCloneURL: https://github.com/akshaygirpunje/spring-boot-http-gradle.git
  org: akshaygirpunje
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: spring-boot-http-gradle
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/akshaygirpunje/spring-boot-http-gradle.git
