adminUser:
  password: local:jenkinsx/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: akshaygirpunje@gmail.com
  token: local:jenkinsx/pipelineUser:token
  username: akshaygirpunje
prow:
  hmacToken: local:jenkinsx/prow:hmacToken
